name: Linters

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install poetry
        python -m poetry install
    - name: Lint with flake8
      run: poetry run flake8 .
    - name: Test with mypy
      run: poetry run mypy .
    - name: Format check with black
      run: poetry run black . --diff
    - name: Format check with isort
      run: poetry run isort . --diff
